<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up():void {
Schema::create('suppliers',function(Blueprint $t){$t->id();$t->text('name_encrypted');$t->text('document_encrypted');$t->char('document_hash',64)->unique();$t->text('email_encrypted');$t->text('phone_encrypted');$t->text('address_encrypted');$t->boolean('active')->default(true)->index();$t->timestamps();$t->softDeletes();});
Schema::create('supplier_products',function(Blueprint $t){$t->id();$t->foreignId('supplier_id')->constrained()->cascadeOnDelete();$t->foreignId('product_id')->constrained()->restrictOnDelete();$t->string('external_code',80);$t->unsignedBigInteger('cost_cents');$t->timestamps();$t->unique(['supplier_id','product_id']);});
Schema::create('purchase_orders',function(Blueprint $t){$t->id();$t->foreignId('supplier_id')->constrained()->restrictOnDelete();$t->string('public_number',40)->unique();$t->string('status',30)->index();$t->unsignedBigInteger('total_cents')->default(0);$t->timestamp('placed_at')->nullable();$t->timestamp('cancelled_at')->nullable();$t->timestamp('received_at')->nullable();$t->timestamps();});
Schema::create('purchase_order_items',function(Blueprint $t){$t->id();$t->foreignId('purchase_order_id')->constrained()->cascadeOnDelete();$t->foreignId('product_id')->constrained()->restrictOnDelete();$t->unsignedInteger('quantity_ordered');$t->unsignedInteger('quantity_received')->default(0);$t->unsignedBigInteger('unit_cost_cents');$t->timestamps();$t->unique(['purchase_order_id','product_id']);});
Schema::create('inventory_items',function(Blueprint $t){$t->id();$t->foreignId('product_id')->unique()->constrained()->restrictOnDelete();$t->unsignedInteger('on_hand')->default(0);$t->unsignedInteger('reserved')->default(0);$t->unsignedInteger('minimum_level')->default(0);$t->timestamps();});
Schema::create('stock_movements',function(Blueprint $t){$t->id();$t->foreignId('inventory_item_id')->constrained()->restrictOnDelete();$t->string('type',40)->index();$t->integer('quantity_delta');$t->uuid('idempotency_key')->unique();$t->nullableMorphs('reference');$t->string('reason',500)->nullable();$t->foreignId('actor_id')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();}); }
public function down():void{Schema::dropIfExists('stock_movements');Schema::dropIfExists('inventory_items');Schema::dropIfExists('purchase_order_items');Schema::dropIfExists('purchase_orders');Schema::dropIfExists('supplier_products');Schema::dropIfExists('suppliers');} };
